name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - python=3.8.16
  - pip=20.3.3
  - pytest=6.2.2
  - scipy=1.6.1
  - pip:
      - wandb==0.10.21
      - numpy==1.20.0
      - protobuf==3.20.1
